// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/syseleven/go-metakube/client/admin"
	"github.com/syseleven/go-metakube/client/aws"
	"github.com/syseleven/go-metakube/client/azure"
	"github.com/syseleven/go-metakube/client/backupcredentials"
	"github.com/syseleven/go-metakube/client/datacenter"
	"github.com/syseleven/go-metakube/client/etcdbackupconfig"
	"github.com/syseleven/go-metakube/client/etcdrestore"
	"github.com/syseleven/go-metakube/client/metric"
	"github.com/syseleven/go-metakube/client/openstack"
	"github.com/syseleven/go-metakube/client/operations"
	"github.com/syseleven/go-metakube/client/project"
	"github.com/syseleven/go-metakube/client/seed"
	"github.com/syseleven/go-metakube/client/serviceaccounts"
	"github.com/syseleven/go-metakube/client/settings"
	"github.com/syseleven/go-metakube/client/tokens"
	"github.com/syseleven/go-metakube/client/users"
	"github.com/syseleven/go-metakube/client/version"
	"github.com/syseleven/go-metakube/client/versions"
)

// Default meta kube API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "metakube.syseleven.de"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new meta kube API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *MetaKubeAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new meta kube API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *MetaKubeAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new meta kube API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *MetaKubeAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(MetaKubeAPI)
	cli.Transport = transport
	cli.Admin = admin.New(transport, formats)
	cli.Aws = aws.New(transport, formats)
	cli.Azure = azure.New(transport, formats)
	cli.Backupcredentials = backupcredentials.New(transport, formats)
	cli.Datacenter = datacenter.New(transport, formats)
	cli.Etcdbackupconfig = etcdbackupconfig.New(transport, formats)
	cli.Etcdrestore = etcdrestore.New(transport, formats)
	cli.Metric = metric.New(transport, formats)
	cli.Openstack = openstack.New(transport, formats)
	cli.Operations = operations.New(transport, formats)
	cli.Project = project.New(transport, formats)
	cli.Seed = seed.New(transport, formats)
	cli.Serviceaccounts = serviceaccounts.New(transport, formats)
	cli.Settings = settings.New(transport, formats)
	cli.Tokens = tokens.New(transport, formats)
	cli.Users = users.New(transport, formats)
	cli.Version = version.New(transport, formats)
	cli.Versions = versions.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// MetaKubeAPI is a client for meta kube API
type MetaKubeAPI struct {
	Admin admin.ClientService

	Aws aws.ClientService

	Azure azure.ClientService

	Backupcredentials backupcredentials.ClientService

	Datacenter datacenter.ClientService

	Etcdbackupconfig etcdbackupconfig.ClientService

	Etcdrestore etcdrestore.ClientService

	Metric metric.ClientService

	Openstack openstack.ClientService

	Operations operations.ClientService

	Project project.ClientService

	Seed seed.ClientService

	Serviceaccounts serviceaccounts.ClientService

	Settings settings.ClientService

	Tokens tokens.ClientService

	Users users.ClientService

	Version version.ClientService

	Versions versions.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *MetaKubeAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Admin.SetTransport(transport)
	c.Aws.SetTransport(transport)
	c.Azure.SetTransport(transport)
	c.Backupcredentials.SetTransport(transport)
	c.Datacenter.SetTransport(transport)
	c.Etcdbackupconfig.SetTransport(transport)
	c.Etcdrestore.SetTransport(transport)
	c.Metric.SetTransport(transport)
	c.Openstack.SetTransport(transport)
	c.Operations.SetTransport(transport)
	c.Project.SetTransport(transport)
	c.Seed.SetTransport(transport)
	c.Serviceaccounts.SetTransport(transport)
	c.Settings.SetTransport(transport)
	c.Tokens.SetTransport(transport)
	c.Users.SetTransport(transport)
	c.Version.SetTransport(transport)
	c.Versions.SetTransport(transport)
}
