// Code generated by go-swagger; DO NOT EDIT.

package backupcredentials

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new backupcredentials API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new backupcredentials API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new backupcredentials API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for backupcredentials API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// CreateOrUpdateBackupCredentials Creates or updates backup credentials for a given seed.
	CreateOrUpdateBackupCredentials(params *CreateOrUpdateBackupCredentialsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateOrUpdateBackupCredentialsOK, error)

	// CreateOrUpdateBackupCredentialsContext Creates or updates backup credentials for a given seed.
	CreateOrUpdateBackupCredentialsContext(ctx context.Context, params *CreateOrUpdateBackupCredentialsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateOrUpdateBackupCredentialsOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// CreateOrUpdateBackupCredentials Creates or updates backup credentials for a given seed.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.CreateOrUpdateBackupCredentialsContext] instead.
func (a *Client) CreateOrUpdateBackupCredentials(params *CreateOrUpdateBackupCredentialsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateOrUpdateBackupCredentialsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.CreateOrUpdateBackupCredentialsContext(ctx, params, authInfo, opts...)
}

// CreateOrUpdateBackupCredentialsContext Creates or updates backup credentials for a given seed.
//
// Do not use the deprecated [CreateOrUpdateBackupCredentialsParams.Context] with this method: it would be ignored.
func (a *Client) CreateOrUpdateBackupCredentialsContext(ctx context.Context, params *CreateOrUpdateBackupCredentialsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateOrUpdateBackupCredentialsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewCreateOrUpdateBackupCredentialsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "createOrUpdateBackupCredentials",
		Method:             "PUT",
		PathPattern:        "/api/v2/seeds/{seed_name}/backupcredentials",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateOrUpdateBackupCredentialsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*CreateOrUpdateBackupCredentialsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*CreateOrUpdateBackupCredentialsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [BackupcredentialsParams].
	ctx context.Context
}
