// Code generated by go-swagger; DO NOT EDIT.

package datacenter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new datacenter API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for datacenter API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetDCForProvider(params *GetDCForProviderParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetDCForProviderOK, error)

	ListDCForProvider(params *ListDCForProviderParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListDCForProviderOK, error)

	ListDatacenters(params *ListDatacentersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListDatacentersOK, error)

	ListDatacentersV2(params *ListDatacentersV2Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListDatacentersV2OK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetDCForProvider gets the datacenter for the specified provider
*/
func (a *Client) GetDCForProvider(params *GetDCForProviderParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetDCForProviderOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDCForProviderParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getDCForProvider",
		Method:             "GET",
		PathPattern:        "/api/v1/providers/{provider_name}/dc/{dc}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetDCForProviderReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDCForProviderOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetDCForProviderDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListDCForProvider returns all datacenters for the specified provider
*/
func (a *Client) ListDCForProvider(params *ListDCForProviderParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListDCForProviderOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListDCForProviderParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "listDCForProvider",
		Method:             "GET",
		PathPattern:        "/api/v1/providers/{provider_name}/dc",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListDCForProviderReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListDCForProviderOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListDCForProviderDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListDatacenters list datacenters API
*/
func (a *Client) ListDatacenters(params *ListDatacentersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListDatacentersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListDatacentersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "listDatacenters",
		Method:             "GET",
		PathPattern:        "/api/v1/dc",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListDatacentersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListDatacentersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListDatacentersDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListDatacentersV2 Lists datacenters
*/
func (a *Client) ListDatacentersV2(params *ListDatacentersV2Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListDatacentersV2OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListDatacentersV2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "listDatacentersV2",
		Method:             "GET",
		PathPattern:        "/api/v2/datacenters",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListDatacentersV2Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListDatacentersV2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListDatacentersV2Default)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
