// Code generated by go-swagger; DO NOT EDIT.

package etcdrestore

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new etcdrestore API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new etcdrestore API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new etcdrestore API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for etcdrestore API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// CreateEtcdRestore Creates a etcd backup restore for a given cluster.
	CreateEtcdRestore(params *CreateEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEtcdRestoreCreated, error)

	// CreateEtcdRestoreContext Creates a etcd backup restore for a given cluster.
	CreateEtcdRestoreContext(ctx context.Context, params *CreateEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEtcdRestoreCreated, error)

	// DeleteEtcdRestore Deletes a etcd restore config for a given cluster based on its name.
	DeleteEtcdRestore(params *DeleteEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteEtcdRestoreOK, error)

	// DeleteEtcdRestoreContext Deletes a etcd restore config for a given cluster based on its name.
	DeleteEtcdRestoreContext(ctx context.Context, params *DeleteEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteEtcdRestoreOK, error)

	// GetEtcdRestore Gets a etcd backup restore for a given cluster based on its name.
	GetEtcdRestore(params *GetEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEtcdRestoreOK, error)

	// GetEtcdRestoreContext Gets a etcd backup restore for a given cluster based on its name.
	GetEtcdRestoreContext(ctx context.Context, params *GetEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEtcdRestoreOK, error)

	// ListEtcdRestore List etcd backup restores for a given cluster.
	ListEtcdRestore(params *ListEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListEtcdRestoreOK, error)

	// ListEtcdRestoreContext List etcd backup restores for a given cluster.
	ListEtcdRestoreContext(ctx context.Context, params *ListEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListEtcdRestoreOK, error)

	// ListProjectEtcdRestore List etcd backup restores for a given project.
	ListProjectEtcdRestore(params *ListProjectEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEtcdRestoreOK, error)

	// ListProjectEtcdRestoreContext List etcd backup restores for a given project.
	ListProjectEtcdRestoreContext(ctx context.Context, params *ListProjectEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEtcdRestoreOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// CreateEtcdRestore Creates a etcd backup restore for a given cluster.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.CreateEtcdRestoreContext] instead.
func (a *Client) CreateEtcdRestore(params *CreateEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEtcdRestoreCreated, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.CreateEtcdRestoreContext(ctx, params, authInfo, opts...)
}

// CreateEtcdRestoreContext Creates a etcd backup restore for a given cluster.
//
// Do not use the deprecated [CreateEtcdRestoreParams.Context] with this method: it would be ignored.
func (a *Client) CreateEtcdRestoreContext(ctx context.Context, params *CreateEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEtcdRestoreCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewCreateEtcdRestoreParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "createEtcdRestore",
		Method:             "POST",
		PathPattern:        "/api/v2/projects/{project_id}/clusters/{cluster_id}/etcdrestores",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateEtcdRestoreReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*CreateEtcdRestoreCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*CreateEtcdRestoreDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// DeleteEtcdRestore Deletes a etcd restore config for a given cluster based on its name.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteEtcdRestoreContext] instead.
func (a *Client) DeleteEtcdRestore(params *DeleteEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteEtcdRestoreOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteEtcdRestoreContext(ctx, params, authInfo, opts...)
}

// DeleteEtcdRestoreContext Deletes a etcd restore config for a given cluster based on its name.
//
// Do not use the deprecated [DeleteEtcdRestoreParams.Context] with this method: it would be ignored.
func (a *Client) DeleteEtcdRestoreContext(ctx context.Context, params *DeleteEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteEtcdRestoreOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteEtcdRestoreParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "deleteEtcdRestore",
		Method:             "DELETE",
		PathPattern:        "/api/v2/projects/{project_id}/clusters/{cluster_id}/etcdrestores/{er_name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteEtcdRestoreReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteEtcdRestoreOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*DeleteEtcdRestoreDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// GetEtcdRestore Gets a etcd backup restore for a given cluster based on its name.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetEtcdRestoreContext] instead.
func (a *Client) GetEtcdRestore(params *GetEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEtcdRestoreOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetEtcdRestoreContext(ctx, params, authInfo, opts...)
}

// GetEtcdRestoreContext Gets a etcd backup restore for a given cluster based on its name.
//
// Do not use the deprecated [GetEtcdRestoreParams.Context] with this method: it would be ignored.
func (a *Client) GetEtcdRestoreContext(ctx context.Context, params *GetEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEtcdRestoreOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetEtcdRestoreParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getEtcdRestore",
		Method:             "GET",
		PathPattern:        "/api/v2/projects/{project_id}/clusters/{cluster_id}/etcdrestores/{er_name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetEtcdRestoreReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetEtcdRestoreOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetEtcdRestoreDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// ListEtcdRestore List etcd backup restores for a given cluster.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.ListEtcdRestoreContext] instead.
func (a *Client) ListEtcdRestore(params *ListEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListEtcdRestoreOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.ListEtcdRestoreContext(ctx, params, authInfo, opts...)
}

// ListEtcdRestoreContext List etcd backup restores for a given cluster.
//
// Do not use the deprecated [ListEtcdRestoreParams.Context] with this method: it would be ignored.
func (a *Client) ListEtcdRestoreContext(ctx context.Context, params *ListEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListEtcdRestoreOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListEtcdRestoreParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "listEtcdRestore",
		Method:             "GET",
		PathPattern:        "/api/v2/projects/{project_id}/clusters/{cluster_id}/etcdrestores",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListEtcdRestoreReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListEtcdRestoreOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*ListEtcdRestoreDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// ListProjectEtcdRestore List etcd backup restores for a given project.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.ListProjectEtcdRestoreContext] instead.
func (a *Client) ListProjectEtcdRestore(params *ListProjectEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEtcdRestoreOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.ListProjectEtcdRestoreContext(ctx, params, authInfo, opts...)
}

// ListProjectEtcdRestoreContext List etcd backup restores for a given project.
//
// Do not use the deprecated [ListProjectEtcdRestoreParams.Context] with this method: it would be ignored.
func (a *Client) ListProjectEtcdRestoreContext(ctx context.Context, params *ListProjectEtcdRestoreParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEtcdRestoreOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListProjectEtcdRestoreParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "listProjectEtcdRestore",
		Method:             "GET",
		PathPattern:        "/api/v2/projects/{project_id}/etcdrestores",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListProjectEtcdRestoreReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListProjectEtcdRestoreOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*ListProjectEtcdRestoreDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [EtcdrestoreParams].
	ctx context.Context
}
