// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/syseleven/go-metakube/models"
)

// NewAddUserToProjectParams creates a new AddUserToProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddUserToProjectParams() *AddUserToProjectParams {
	return NewAddUserToProjectParamsWithTimeout(cr.DefaultTimeout)
}

// NewAddUserToProjectParamsWithTimeout creates a new AddUserToProjectParams object
// with the ability to set a timeout on a request.
func NewAddUserToProjectParamsWithTimeout(timeout time.Duration) *AddUserToProjectParams {
	return &AddUserToProjectParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewAddUserToProjectParamsWithContext creates a new AddUserToProjectParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [AddUserToProjectParams].
func NewAddUserToProjectParamsWithContext(ctx context.Context) *AddUserToProjectParams {
	return &AddUserToProjectParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewAddUserToProjectParamsWithHTTPClient creates a new AddUserToProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddUserToProjectParamsWithHTTPClient(client *http.Client) *AddUserToProjectParams {
	return &AddUserToProjectParams{
		HTTPClient: client,
	}
}

/*
AddUserToProjectParams contains all the parameters to send to the API endpoint

	for the add user to project operation.

	Typically these are written to a http.Request.
*/
type AddUserToProjectParams struct {

	// Body.
	Body *models.User

	// ProjectID.
	ProjectID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the add user to project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddUserToProjectParams) WithDefaults() *AddUserToProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add user to project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddUserToProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add user to project params.
func (o *AddUserToProjectParams) WithTimeout(timeout time.Duration) *AddUserToProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add user to project params.
func (o *AddUserToProjectParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the add user to project params.
//
// Deprecated: use the operation call with context to pass the context instead of [AddUserToProjectParams].
func (o *AddUserToProjectParams) WithContext(ctx context.Context) *AddUserToProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add user to project params.
//
// Deprecated: use the operation call with context to pass the context instead of [AddUserToProjectParams].
func (o *AddUserToProjectParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the add user to project params.
func (o *AddUserToProjectParams) WithHTTPClient(client *http.Client) *AddUserToProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add user to project params.
func (o *AddUserToProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add user to project params.
func (o *AddUserToProjectParams) WithBody(body *models.User) *AddUserToProjectParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add user to project params.
func (o *AddUserToProjectParams) SetBody(body *models.User) {
	o.Body = body
}

// WithProjectID adds the projectID to the add user to project params.
func (o *AddUserToProjectParams) WithProjectID(projectID string) *AddUserToProjectParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the add user to project params.
func (o *AddUserToProjectParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *AddUserToProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
