// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new users API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new users API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new users API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for users API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// AddUserToProject Adds the given user to the given project.
	AddUserToProject(params *AddUserToProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddUserToProjectCreated, error)

	// AddUserToProjectContext Adds the given user to the given project.
	AddUserToProjectContext(ctx context.Context, params *AddUserToProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddUserToProjectCreated, error)

	// DeleteUserFromProject Removes the given member from the project.
	DeleteUserFromProject(params *DeleteUserFromProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteUserFromProjectOK, error)

	// DeleteUserFromProjectContext Removes the given member from the project.
	DeleteUserFromProjectContext(ctx context.Context, params *DeleteUserFromProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteUserFromProjectOK, error)

	// EditUserInProject Changes membership of the given user for the given project.
	EditUserInProject(params *EditUserInProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*EditUserInProjectOK, error)

	// EditUserInProjectContext Changes membership of the given user for the given project.
	EditUserInProjectContext(ctx context.Context, params *EditUserInProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*EditUserInProjectOK, error)

	// GetCurrentUser returns information about the current user.
	GetCurrentUser(params *GetCurrentUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserOK, error)

	// GetCurrentUserContext returns information about the current user.
	GetCurrentUserContext(ctx context.Context, params *GetCurrentUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserOK, error)

	// GetUsersForProject Get list of users for the given project.
	GetUsersForProject(params *GetUsersForProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetUsersForProjectOK, error)

	// GetUsersForProjectContext Get list of users for the given project.
	GetUsersForProjectContext(ctx context.Context, params *GetUsersForProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetUsersForProjectOK, error)

	// LogoutCurrentUser adds current authorization bearer token to the blacklist.
	LogoutCurrentUser(params *LogoutCurrentUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*LogoutCurrentUserOK, error)

	// LogoutCurrentUserContext adds current authorization bearer token to the blacklist.
	LogoutCurrentUserContext(ctx context.Context, params *LogoutCurrentUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*LogoutCurrentUserOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// AddUserToProject Adds the given user to the given project.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.AddUserToProjectContext] instead.
func (a *Client) AddUserToProject(params *AddUserToProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddUserToProjectCreated, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.AddUserToProjectContext(ctx, params, authInfo, opts...)
}

// AddUserToProjectContext Adds the given user to the given project.
//
// Do not use the deprecated [AddUserToProjectParams.Context] with this method: it would be ignored.
func (a *Client) AddUserToProjectContext(ctx context.Context, params *AddUserToProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddUserToProjectCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewAddUserToProjectParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "addUserToProject",
		Method:             "POST",
		PathPattern:        "/api/v1/projects/{project_id}/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AddUserToProjectReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*AddUserToProjectCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*AddUserToProjectDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// DeleteUserFromProject Removes the given member from the project.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteUserFromProjectContext] instead.
func (a *Client) DeleteUserFromProject(params *DeleteUserFromProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteUserFromProjectOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteUserFromProjectContext(ctx, params, authInfo, opts...)
}

// DeleteUserFromProjectContext Removes the given member from the project.
//
// Do not use the deprecated [DeleteUserFromProjectParams.Context] with this method: it would be ignored.
func (a *Client) DeleteUserFromProjectContext(ctx context.Context, params *DeleteUserFromProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteUserFromProjectOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteUserFromProjectParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "deleteUserFromProject",
		Method:             "DELETE",
		PathPattern:        "/api/v1/projects/{project_id}/users/{user_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteUserFromProjectReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteUserFromProjectOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*DeleteUserFromProjectDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// EditUserInProject Changes membership of the given user for the given project.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.EditUserInProjectContext] instead.
func (a *Client) EditUserInProject(params *EditUserInProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*EditUserInProjectOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.EditUserInProjectContext(ctx, params, authInfo, opts...)
}

// EditUserInProjectContext Changes membership of the given user for the given project.
//
// Do not use the deprecated [EditUserInProjectParams.Context] with this method: it would be ignored.
func (a *Client) EditUserInProjectContext(ctx context.Context, params *EditUserInProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*EditUserInProjectOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewEditUserInProjectParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "editUserInProject",
		Method:             "PUT",
		PathPattern:        "/api/v1/projects/{project_id}/users/{user_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &EditUserInProjectReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*EditUserInProjectOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*EditUserInProjectDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// GetCurrentUser returns information about the current user.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCurrentUserContext] instead.
func (a *Client) GetCurrentUser(params *GetCurrentUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCurrentUserContext(ctx, params, authInfo, opts...)
}

// GetCurrentUserContext returns information about the current user.
//
// Do not use the deprecated [GetCurrentUserParams.Context] with this method: it would be ignored.
func (a *Client) GetCurrentUserContext(ctx context.Context, params *GetCurrentUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCurrentUserParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getCurrentUser",
		Method:             "GET",
		PathPattern:        "/api/v1/me",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCurrentUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCurrentUserOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetCurrentUserDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// GetUsersForProject Get list of users for the given project.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetUsersForProjectContext] instead.
func (a *Client) GetUsersForProject(params *GetUsersForProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetUsersForProjectOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetUsersForProjectContext(ctx, params, authInfo, opts...)
}

// GetUsersForProjectContext Get list of users for the given project.
//
// Do not use the deprecated [GetUsersForProjectParams.Context] with this method: it would be ignored.
func (a *Client) GetUsersForProjectContext(ctx context.Context, params *GetUsersForProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetUsersForProjectOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetUsersForProjectParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getUsersForProject",
		Method:             "GET",
		PathPattern:        "/api/v1/projects/{project_id}/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetUsersForProjectReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetUsersForProjectOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetUsersForProjectDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// LogoutCurrentUser adds current authorization bearer token to the blacklist.
//
// Enforces user to login again with the new token..
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.LogoutCurrentUserContext] instead.
func (a *Client) LogoutCurrentUser(params *LogoutCurrentUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*LogoutCurrentUserOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.LogoutCurrentUserContext(ctx, params, authInfo, opts...)
}

// LogoutCurrentUserContext adds current authorization bearer token to the blacklist.
//
// Enforces user to login again with the new token..
//
// Do not use the deprecated [LogoutCurrentUserParams.Context] with this method: it would be ignored.
func (a *Client) LogoutCurrentUserContext(ctx context.Context, params *LogoutCurrentUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*LogoutCurrentUserOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewLogoutCurrentUserParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "logoutCurrentUser",
		Method:             "POST",
		PathPattern:        "/api/v1/me/logout",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &LogoutCurrentUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*LogoutCurrentUserOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*LogoutCurrentUserDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [UsersParams].
	ctx context.Context
}
