// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSeedParams creates a new GetSeedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSeedParams() *GetSeedParams {
	return NewGetSeedParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetSeedParamsWithTimeout creates a new GetSeedParams object
// with the ability to set a timeout on a request.
func NewGetSeedParamsWithTimeout(timeout time.Duration) *GetSeedParams {
	return &GetSeedParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetSeedParamsWithContext creates a new GetSeedParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetSeedParams].
func NewGetSeedParamsWithContext(ctx context.Context) *GetSeedParams {
	return &GetSeedParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetSeedParamsWithHTTPClient creates a new GetSeedParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSeedParamsWithHTTPClient(client *http.Client) *GetSeedParams {
	return &GetSeedParams{
		HTTPClient: client,
	}
}

/*
GetSeedParams contains all the parameters to send to the API endpoint

	for the get seed operation.

	Typically these are written to a http.Request.
*/
type GetSeedParams struct {

	// SeedName.
	Name string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get seed params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSeedParams) WithDefaults() *GetSeedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get seed params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSeedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get seed params.
func (o *GetSeedParams) WithTimeout(timeout time.Duration) *GetSeedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get seed params.
func (o *GetSeedParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get seed params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetSeedParams].
func (o *GetSeedParams) WithContext(ctx context.Context) *GetSeedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get seed params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetSeedParams].
func (o *GetSeedParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get seed params.
func (o *GetSeedParams) WithHTTPClient(client *http.Client) *GetSeedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get seed params.
func (o *GetSeedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the seedName to the get seed params.
func (o *GetSeedParams) WithName(seedName string) *GetSeedParams {
	o.SetName(seedName)
	return o
}

// SetName adds the seedName to the get seed params.
func (o *GetSeedParams) SetName(seedName string) {
	o.Name = seedName
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetSeedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param seed_name
	if err := r.SetPathParam("seed_name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
