// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchKubermaticSettingsParams creates a new PatchKubermaticSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchKubermaticSettingsParams() *PatchKubermaticSettingsParams {
	return NewPatchKubermaticSettingsParamsWithTimeout(cr.DefaultTimeout)
}

// NewPatchKubermaticSettingsParamsWithTimeout creates a new PatchKubermaticSettingsParams object
// with the ability to set a timeout on a request.
func NewPatchKubermaticSettingsParamsWithTimeout(timeout time.Duration) *PatchKubermaticSettingsParams {
	return &PatchKubermaticSettingsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPatchKubermaticSettingsParamsWithContext creates a new PatchKubermaticSettingsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PatchKubermaticSettingsParams].
func NewPatchKubermaticSettingsParamsWithContext(ctx context.Context) *PatchKubermaticSettingsParams {
	return &PatchKubermaticSettingsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPatchKubermaticSettingsParamsWithHTTPClient creates a new PatchKubermaticSettingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchKubermaticSettingsParamsWithHTTPClient(client *http.Client) *PatchKubermaticSettingsParams {
	return &PatchKubermaticSettingsParams{
		HTTPClient: client,
	}
}

/*
PatchKubermaticSettingsParams contains all the parameters to send to the API endpoint

	for the patch kubermatic settings operation.

	Typically these are written to a http.Request.
*/
type PatchKubermaticSettingsParams struct {

	// Patch.
	Patch any

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the patch kubermatic settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchKubermaticSettingsParams) WithDefaults() *PatchKubermaticSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch kubermatic settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchKubermaticSettingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch kubermatic settings params.
func (o *PatchKubermaticSettingsParams) WithTimeout(timeout time.Duration) *PatchKubermaticSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch kubermatic settings params.
func (o *PatchKubermaticSettingsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the patch kubermatic settings params.
//
// Deprecated: use the operation call with context to pass the context instead of [PatchKubermaticSettingsParams].
func (o *PatchKubermaticSettingsParams) WithContext(ctx context.Context) *PatchKubermaticSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch kubermatic settings params.
//
// Deprecated: use the operation call with context to pass the context instead of [PatchKubermaticSettingsParams].
func (o *PatchKubermaticSettingsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the patch kubermatic settings params.
func (o *PatchKubermaticSettingsParams) WithHTTPClient(client *http.Client) *PatchKubermaticSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch kubermatic settings params.
func (o *PatchKubermaticSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPatch adds the patch to the patch kubermatic settings params.
func (o *PatchKubermaticSettingsParams) WithPatch(patch any) *PatchKubermaticSettingsParams {
	o.SetPatch(patch)
	return o
}

// SetPatch adds the patch to the patch kubermatic settings params.
func (o *PatchKubermaticSettingsParams) SetPatch(patch any) {
	o.Patch = patch
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PatchKubermaticSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Patch != nil {
		if err := r.SetBodyParam(o.Patch); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
