// Code generated by go-swagger; DO NOT EDIT.

package tokens

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new tokens API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new tokens API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new tokens API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for tokens API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// AddTokenToServiceAccount Generates a token for the given service account.
	AddTokenToServiceAccount(params *AddTokenToServiceAccountParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddTokenToServiceAccountCreated, error)

	// AddTokenToServiceAccountContext Generates a token for the given service account.
	AddTokenToServiceAccountContext(ctx context.Context, params *AddTokenToServiceAccountParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddTokenToServiceAccountCreated, error)

	// DeleteServiceAccountToken Deletes the token.
	DeleteServiceAccountToken(params *DeleteServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteServiceAccountTokenOK, error)

	// DeleteServiceAccountTokenContext Deletes the token.
	DeleteServiceAccountTokenContext(ctx context.Context, params *DeleteServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteServiceAccountTokenOK, error)

	// ListServiceAccountTokens List tokens for the given service account.
	ListServiceAccountTokens(params *ListServiceAccountTokensParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListServiceAccountTokensOK, error)

	// ListServiceAccountTokensContext List tokens for the given service account.
	ListServiceAccountTokensContext(ctx context.Context, params *ListServiceAccountTokensParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListServiceAccountTokensOK, error)

	// PatchServiceAccountToken Patches the token name.
	PatchServiceAccountToken(params *PatchServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchServiceAccountTokenOK, error)

	// PatchServiceAccountTokenContext Patches the token name.
	PatchServiceAccountTokenContext(ctx context.Context, params *PatchServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchServiceAccountTokenOK, error)

	// UpdateServiceAccountToken Updates and regenerates the token.
	UpdateServiceAccountToken(params *UpdateServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateServiceAccountTokenOK, error)

	// UpdateServiceAccountTokenContext Updates and regenerates the token.
	UpdateServiceAccountTokenContext(ctx context.Context, params *UpdateServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateServiceAccountTokenOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// AddTokenToServiceAccount Generates a token for the given service account.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.AddTokenToServiceAccountContext] instead.
func (a *Client) AddTokenToServiceAccount(params *AddTokenToServiceAccountParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddTokenToServiceAccountCreated, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.AddTokenToServiceAccountContext(ctx, params, authInfo, opts...)
}

// AddTokenToServiceAccountContext Generates a token for the given service account.
//
// Do not use the deprecated [AddTokenToServiceAccountParams.Context] with this method: it would be ignored.
func (a *Client) AddTokenToServiceAccountContext(ctx context.Context, params *AddTokenToServiceAccountParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddTokenToServiceAccountCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewAddTokenToServiceAccountParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "addTokenToServiceAccount",
		Method:             "POST",
		PathPattern:        "/api/v1/projects/{project_id}/serviceaccounts/{serviceaccount_id}/tokens",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AddTokenToServiceAccountReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*AddTokenToServiceAccountCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*AddTokenToServiceAccountDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// DeleteServiceAccountToken Deletes the token.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteServiceAccountTokenContext] instead.
func (a *Client) DeleteServiceAccountToken(params *DeleteServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteServiceAccountTokenOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteServiceAccountTokenContext(ctx, params, authInfo, opts...)
}

// DeleteServiceAccountTokenContext Deletes the token.
//
// Do not use the deprecated [DeleteServiceAccountTokenParams.Context] with this method: it would be ignored.
func (a *Client) DeleteServiceAccountTokenContext(ctx context.Context, params *DeleteServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteServiceAccountTokenOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteServiceAccountTokenParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "deleteServiceAccountToken",
		Method:             "DELETE",
		PathPattern:        "/api/v1/projects/{project_id}/serviceaccounts/{serviceaccount_id}/tokens/{token_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteServiceAccountTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteServiceAccountTokenOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*DeleteServiceAccountTokenDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// ListServiceAccountTokens List tokens for the given service account.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.ListServiceAccountTokensContext] instead.
func (a *Client) ListServiceAccountTokens(params *ListServiceAccountTokensParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListServiceAccountTokensOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.ListServiceAccountTokensContext(ctx, params, authInfo, opts...)
}

// ListServiceAccountTokensContext List tokens for the given service account.
//
// Do not use the deprecated [ListServiceAccountTokensParams.Context] with this method: it would be ignored.
func (a *Client) ListServiceAccountTokensContext(ctx context.Context, params *ListServiceAccountTokensParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListServiceAccountTokensOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListServiceAccountTokensParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "listServiceAccountTokens",
		Method:             "GET",
		PathPattern:        "/api/v1/projects/{project_id}/serviceaccounts/{serviceaccount_id}/tokens",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListServiceAccountTokensReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListServiceAccountTokensOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*ListServiceAccountTokensDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// PatchServiceAccountToken Patches the token name.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PatchServiceAccountTokenContext] instead.
func (a *Client) PatchServiceAccountToken(params *PatchServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchServiceAccountTokenOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PatchServiceAccountTokenContext(ctx, params, authInfo, opts...)
}

// PatchServiceAccountTokenContext Patches the token name.
//
// Do not use the deprecated [PatchServiceAccountTokenParams.Context] with this method: it would be ignored.
func (a *Client) PatchServiceAccountTokenContext(ctx context.Context, params *PatchServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchServiceAccountTokenOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPatchServiceAccountTokenParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "patchServiceAccountToken",
		Method:             "PATCH",
		PathPattern:        "/api/v1/projects/{project_id}/serviceaccounts/{serviceaccount_id}/tokens/{token_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PatchServiceAccountTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PatchServiceAccountTokenOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PatchServiceAccountTokenDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// UpdateServiceAccountToken Updates and regenerates the token.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.UpdateServiceAccountTokenContext] instead.
func (a *Client) UpdateServiceAccountToken(params *UpdateServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateServiceAccountTokenOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.UpdateServiceAccountTokenContext(ctx, params, authInfo, opts...)
}

// UpdateServiceAccountTokenContext Updates and regenerates the token.
//
// Do not use the deprecated [UpdateServiceAccountTokenParams.Context] with this method: it would be ignored.
func (a *Client) UpdateServiceAccountTokenContext(ctx context.Context, params *UpdateServiceAccountTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateServiceAccountTokenOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewUpdateServiceAccountTokenParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "updateServiceAccountToken",
		Method:             "PUT",
		PathPattern:        "/api/v1/projects/{project_id}/serviceaccounts/{serviceaccount_id}/tokens/{token_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateServiceAccountTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*UpdateServiceAccountTokenOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*UpdateServiceAccountTokenDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [TokensParams].
	ctx context.Context
}
