// Code generated by go-swagger; DO NOT EDIT.

package versions

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMetaKubeVersionsParams creates a new GetMetaKubeVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMetaKubeVersionsParams() *GetMetaKubeVersionsParams {
	return NewGetMetaKubeVersionsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetMetaKubeVersionsParamsWithTimeout creates a new GetMetaKubeVersionsParams object
// with the ability to set a timeout on a request.
func NewGetMetaKubeVersionsParamsWithTimeout(timeout time.Duration) *GetMetaKubeVersionsParams {
	return &GetMetaKubeVersionsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetMetaKubeVersionsParamsWithContext creates a new GetMetaKubeVersionsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetMetaKubeVersionsParams].
func NewGetMetaKubeVersionsParamsWithContext(ctx context.Context) *GetMetaKubeVersionsParams {
	return &GetMetaKubeVersionsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetMetaKubeVersionsParamsWithHTTPClient creates a new GetMetaKubeVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMetaKubeVersionsParamsWithHTTPClient(client *http.Client) *GetMetaKubeVersionsParams {
	return &GetMetaKubeVersionsParams{
		HTTPClient: client,
	}
}

/*
GetMetaKubeVersionsParams contains all the parameters to send to the API endpoint

	for the get meta kube versions operation.

	Typically these are written to a http.Request.
*/
type GetMetaKubeVersionsParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get meta kube versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetaKubeVersionsParams) WithDefaults() *GetMetaKubeVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get meta kube versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetaKubeVersionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get meta kube versions params.
func (o *GetMetaKubeVersionsParams) WithTimeout(timeout time.Duration) *GetMetaKubeVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get meta kube versions params.
func (o *GetMetaKubeVersionsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get meta kube versions params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetMetaKubeVersionsParams].
func (o *GetMetaKubeVersionsParams) WithContext(ctx context.Context) *GetMetaKubeVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get meta kube versions params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetMetaKubeVersionsParams].
func (o *GetMetaKubeVersionsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get meta kube versions params.
func (o *GetMetaKubeVersionsParams) WithHTTPClient(client *http.Client) *GetMetaKubeVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get meta kube versions params.
func (o *GetMetaKubeVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetMetaKubeVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
