// Code generated by go-swagger; DO NOT EDIT.

package etcdbackupconfig

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new etcdbackupconfig API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new etcdbackupconfig API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new etcdbackupconfig API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for etcdbackupconfig API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// CreateEtcdBackupConfig Creates a etcd backup config that will belong to the given cluster.
	CreateEtcdBackupConfig(params *CreateEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEtcdBackupConfigCreated, error)

	// CreateEtcdBackupConfigContext Creates a etcd backup config that will belong to the given cluster.
	CreateEtcdBackupConfigContext(ctx context.Context, params *CreateEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEtcdBackupConfigCreated, error)

	// DeleteEtcdBackupConfig Deletes a etcd backup config for a given cluster based on its id.
	DeleteEtcdBackupConfig(params *DeleteEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteEtcdBackupConfigOK, error)

	// DeleteEtcdBackupConfigContext Deletes a etcd backup config for a given cluster based on its id.
	DeleteEtcdBackupConfigContext(ctx context.Context, params *DeleteEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteEtcdBackupConfigOK, error)

	// GetEtcdBackupConfig Gets a etcd backup config for a given cluster based on its id.
	GetEtcdBackupConfig(params *GetEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEtcdBackupConfigOK, error)

	// GetEtcdBackupConfigContext Gets a etcd backup config for a given cluster based on its id.
	GetEtcdBackupConfigContext(ctx context.Context, params *GetEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEtcdBackupConfigOK, error)

	// ListEtcdBackupConfig List etcd backup configs for a given cluster.
	ListEtcdBackupConfig(params *ListEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListEtcdBackupConfigOK, error)

	// ListEtcdBackupConfigContext List etcd backup configs for a given cluster.
	ListEtcdBackupConfigContext(ctx context.Context, params *ListEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListEtcdBackupConfigOK, error)

	// ListProjectEtcdBackupConfig List etcd backup configs for a given project.
	ListProjectEtcdBackupConfig(params *ListProjectEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEtcdBackupConfigOK, error)

	// ListProjectEtcdBackupConfigContext List etcd backup configs for a given project.
	ListProjectEtcdBackupConfigContext(ctx context.Context, params *ListProjectEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEtcdBackupConfigOK, error)

	// PatchEtcdBackupConfig Patches a etcd backup config for a given cluster based on its id.
	PatchEtcdBackupConfig(params *PatchEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchEtcdBackupConfigOK, error)

	// PatchEtcdBackupConfigContext Patches a etcd backup config for a given cluster based on its id.
	PatchEtcdBackupConfigContext(ctx context.Context, params *PatchEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchEtcdBackupConfigOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// CreateEtcdBackupConfig Creates a etcd backup config that will belong to the given cluster.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.CreateEtcdBackupConfigContext] instead.
func (a *Client) CreateEtcdBackupConfig(params *CreateEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEtcdBackupConfigCreated, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.CreateEtcdBackupConfigContext(ctx, params, authInfo, opts...)
}

// CreateEtcdBackupConfigContext Creates a etcd backup config that will belong to the given cluster.
//
// Do not use the deprecated [CreateEtcdBackupConfigParams.Context] with this method: it would be ignored.
func (a *Client) CreateEtcdBackupConfigContext(ctx context.Context, params *CreateEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEtcdBackupConfigCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewCreateEtcdBackupConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "createEtcdBackupConfig",
		Method:             "POST",
		PathPattern:        "/api/v2/projects/{project_id}/clusters/{cluster_id}/etcdbackupconfigs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateEtcdBackupConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*CreateEtcdBackupConfigCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*CreateEtcdBackupConfigDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// DeleteEtcdBackupConfig Deletes a etcd backup config for a given cluster based on its id.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteEtcdBackupConfigContext] instead.
func (a *Client) DeleteEtcdBackupConfig(params *DeleteEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteEtcdBackupConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteEtcdBackupConfigContext(ctx, params, authInfo, opts...)
}

// DeleteEtcdBackupConfigContext Deletes a etcd backup config for a given cluster based on its id.
//
// Do not use the deprecated [DeleteEtcdBackupConfigParams.Context] with this method: it would be ignored.
func (a *Client) DeleteEtcdBackupConfigContext(ctx context.Context, params *DeleteEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteEtcdBackupConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteEtcdBackupConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "deleteEtcdBackupConfig",
		Method:             "DELETE",
		PathPattern:        "/api/v2/projects/{project_id}/clusters/{cluster_id}/etcdbackupconfigs/{ebc_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteEtcdBackupConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteEtcdBackupConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*DeleteEtcdBackupConfigDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// GetEtcdBackupConfig Gets a etcd backup config for a given cluster based on its id.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetEtcdBackupConfigContext] instead.
func (a *Client) GetEtcdBackupConfig(params *GetEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEtcdBackupConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetEtcdBackupConfigContext(ctx, params, authInfo, opts...)
}

// GetEtcdBackupConfigContext Gets a etcd backup config for a given cluster based on its id.
//
// Do not use the deprecated [GetEtcdBackupConfigParams.Context] with this method: it would be ignored.
func (a *Client) GetEtcdBackupConfigContext(ctx context.Context, params *GetEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEtcdBackupConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetEtcdBackupConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getEtcdBackupConfig",
		Method:             "GET",
		PathPattern:        "/api/v2/projects/{project_id}/clusters/{cluster_id}/etcdbackupconfigs/{ebc_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetEtcdBackupConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetEtcdBackupConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetEtcdBackupConfigDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// ListEtcdBackupConfig List etcd backup configs for a given cluster.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.ListEtcdBackupConfigContext] instead.
func (a *Client) ListEtcdBackupConfig(params *ListEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListEtcdBackupConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.ListEtcdBackupConfigContext(ctx, params, authInfo, opts...)
}

// ListEtcdBackupConfigContext List etcd backup configs for a given cluster.
//
// Do not use the deprecated [ListEtcdBackupConfigParams.Context] with this method: it would be ignored.
func (a *Client) ListEtcdBackupConfigContext(ctx context.Context, params *ListEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListEtcdBackupConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListEtcdBackupConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "listEtcdBackupConfig",
		Method:             "GET",
		PathPattern:        "/api/v2/projects/{project_id}/clusters/{cluster_id}/etcdbackupconfigs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListEtcdBackupConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListEtcdBackupConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*ListEtcdBackupConfigDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// ListProjectEtcdBackupConfig List etcd backup configs for a given project.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.ListProjectEtcdBackupConfigContext] instead.
func (a *Client) ListProjectEtcdBackupConfig(params *ListProjectEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEtcdBackupConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.ListProjectEtcdBackupConfigContext(ctx, params, authInfo, opts...)
}

// ListProjectEtcdBackupConfigContext List etcd backup configs for a given project.
//
// Do not use the deprecated [ListProjectEtcdBackupConfigParams.Context] with this method: it would be ignored.
func (a *Client) ListProjectEtcdBackupConfigContext(ctx context.Context, params *ListProjectEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEtcdBackupConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListProjectEtcdBackupConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "listProjectEtcdBackupConfig",
		Method:             "GET",
		PathPattern:        "/api/v2/projects/{project_id}/etcdbackupconfigs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListProjectEtcdBackupConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListProjectEtcdBackupConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*ListProjectEtcdBackupConfigDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// PatchEtcdBackupConfig Patches a etcd backup config for a given cluster based on its id.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PatchEtcdBackupConfigContext] instead.
func (a *Client) PatchEtcdBackupConfig(params *PatchEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchEtcdBackupConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PatchEtcdBackupConfigContext(ctx, params, authInfo, opts...)
}

// PatchEtcdBackupConfigContext Patches a etcd backup config for a given cluster based on its id.
//
// Do not use the deprecated [PatchEtcdBackupConfigParams.Context] with this method: it would be ignored.
func (a *Client) PatchEtcdBackupConfigContext(ctx context.Context, params *PatchEtcdBackupConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchEtcdBackupConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPatchEtcdBackupConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "patchEtcdBackupConfig",
		Method:             "PATCH",
		PathPattern:        "/api/v2/projects/{project_id}/clusters/{cluster_id}/etcdbackupconfigs/{ebc_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PatchEtcdBackupConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PatchEtcdBackupConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*PatchEtcdBackupConfigDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [EtcdbackupconfigParams].
	ctx context.Context
}
