// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteMachineDeploymentNodeParams creates a new DeleteMachineDeploymentNodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteMachineDeploymentNodeParams() *DeleteMachineDeploymentNodeParams {
	return NewDeleteMachineDeploymentNodeParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteMachineDeploymentNodeParamsWithTimeout creates a new DeleteMachineDeploymentNodeParams object
// with the ability to set a timeout on a request.
func NewDeleteMachineDeploymentNodeParamsWithTimeout(timeout time.Duration) *DeleteMachineDeploymentNodeParams {
	return &DeleteMachineDeploymentNodeParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteMachineDeploymentNodeParamsWithContext creates a new DeleteMachineDeploymentNodeParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteMachineDeploymentNodeParams].
func NewDeleteMachineDeploymentNodeParamsWithContext(ctx context.Context) *DeleteMachineDeploymentNodeParams {
	return &DeleteMachineDeploymentNodeParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteMachineDeploymentNodeParamsWithHTTPClient creates a new DeleteMachineDeploymentNodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteMachineDeploymentNodeParamsWithHTTPClient(client *http.Client) *DeleteMachineDeploymentNodeParams {
	return &DeleteMachineDeploymentNodeParams{
		HTTPClient: client,
	}
}

/*
DeleteMachineDeploymentNodeParams contains all the parameters to send to the API endpoint

	for the delete machine deployment node operation.

	Typically these are written to a http.Request.
*/
type DeleteMachineDeploymentNodeParams struct {

	// ClusterID.
	ClusterID string

	// NodeID.
	NodeID string

	// ProjectID.
	ProjectID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete machine deployment node params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMachineDeploymentNodeParams) WithDefaults() *DeleteMachineDeploymentNodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete machine deployment node params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMachineDeploymentNodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) WithTimeout(timeout time.Duration) *DeleteMachineDeploymentNodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete machine deployment node params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteMachineDeploymentNodeParams].
func (o *DeleteMachineDeploymentNodeParams) WithContext(ctx context.Context) *DeleteMachineDeploymentNodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete machine deployment node params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteMachineDeploymentNodeParams].
func (o *DeleteMachineDeploymentNodeParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) WithHTTPClient(client *http.Client) *DeleteMachineDeploymentNodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) WithClusterID(clusterID string) *DeleteMachineDeploymentNodeParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithNodeID adds the nodeID to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) WithNodeID(nodeID string) *DeleteMachineDeploymentNodeParams {
	o.SetNodeID(nodeID)
	return o
}

// SetNodeID adds the nodeId to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) SetNodeID(nodeID string) {
	o.NodeID = nodeID
}

// WithProjectID adds the projectID to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) WithProjectID(projectID string) *DeleteMachineDeploymentNodeParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete machine deployment node params.
func (o *DeleteMachineDeploymentNodeParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteMachineDeploymentNodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param node_id
	if err := r.SetPathParam("node_id", o.NodeID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
