// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMaintenanceCronJobParams creates a new GetMaintenanceCronJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMaintenanceCronJobParams() *GetMaintenanceCronJobParams {
	return &GetMaintenanceCronJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMaintenanceCronJobParamsWithTimeout creates a new GetMaintenanceCronJobParams object
// with the ability to set a timeout on a request.
func NewGetMaintenanceCronJobParamsWithTimeout(timeout time.Duration) *GetMaintenanceCronJobParams {
	return &GetMaintenanceCronJobParams{
		timeout: timeout,
	}
}

// NewGetMaintenanceCronJobParamsWithContext creates a new GetMaintenanceCronJobParams object
// with the ability to set a context for a request.
func NewGetMaintenanceCronJobParamsWithContext(ctx context.Context) *GetMaintenanceCronJobParams {
	return &GetMaintenanceCronJobParams{
		Context: ctx,
	}
}

// NewGetMaintenanceCronJobParamsWithHTTPClient creates a new GetMaintenanceCronJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMaintenanceCronJobParamsWithHTTPClient(client *http.Client) *GetMaintenanceCronJobParams {
	return &GetMaintenanceCronJobParams{
		HTTPClient: client,
	}
}

/*
GetMaintenanceCronJobParams contains all the parameters to send to the API endpoint

	for the get maintenance cron job operation.

	Typically these are written to a http.Request.
*/
type GetMaintenanceCronJobParams struct {

	// ClusterID.
	ClusterID string

	// MaintenancecronjobID.
	MaintenanceCronJobID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get maintenance cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMaintenanceCronJobParams) WithDefaults() *GetMaintenanceCronJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get maintenance cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMaintenanceCronJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) WithTimeout(timeout time.Duration) *GetMaintenanceCronJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) WithContext(ctx context.Context) *GetMaintenanceCronJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) WithHTTPClient(client *http.Client) *GetMaintenanceCronJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) WithClusterID(clusterID string) *GetMaintenanceCronJobParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithMaintenanceCronJobID adds the maintenancecronjobID to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) WithMaintenanceCronJobID(maintenancecronjobID string) *GetMaintenanceCronJobParams {
	o.SetMaintenanceCronJobID(maintenancecronjobID)
	return o
}

// SetMaintenanceCronJobID adds the maintenancecronjobId to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) SetMaintenanceCronJobID(maintenancecronjobID string) {
	o.MaintenanceCronJobID = maintenancecronjobID
}

// WithProjectID adds the projectID to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) WithProjectID(projectID string) *GetMaintenanceCronJobParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get maintenance cron job params
func (o *GetMaintenanceCronJobParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMaintenanceCronJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param maintenancecronjob_id
	if err := r.SetPathParam("maintenancecronjob_id", o.MaintenanceCronJobID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
