// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListMaintenanceCronJobsParams creates a new ListMaintenanceCronJobsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListMaintenanceCronJobsParams() *ListMaintenanceCronJobsParams {
	return NewListMaintenanceCronJobsParamsWithTimeout(cr.DefaultTimeout)
}

// NewListMaintenanceCronJobsParamsWithTimeout creates a new ListMaintenanceCronJobsParams object
// with the ability to set a timeout on a request.
func NewListMaintenanceCronJobsParamsWithTimeout(timeout time.Duration) *ListMaintenanceCronJobsParams {
	return &ListMaintenanceCronJobsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListMaintenanceCronJobsParamsWithContext creates a new ListMaintenanceCronJobsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListMaintenanceCronJobsParams].
func NewListMaintenanceCronJobsParamsWithContext(ctx context.Context) *ListMaintenanceCronJobsParams {
	return &ListMaintenanceCronJobsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListMaintenanceCronJobsParamsWithHTTPClient creates a new ListMaintenanceCronJobsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListMaintenanceCronJobsParamsWithHTTPClient(client *http.Client) *ListMaintenanceCronJobsParams {
	return &ListMaintenanceCronJobsParams{
		HTTPClient: client,
	}
}

/*
ListMaintenanceCronJobsParams contains all the parameters to send to the API endpoint

	for the list maintenance cron jobs operation.

	Typically these are written to a http.Request.
*/
type ListMaintenanceCronJobsParams struct {

	// ClusterID.
	ClusterID string

	// ProjectID.
	ProjectID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list maintenance cron jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListMaintenanceCronJobsParams) WithDefaults() *ListMaintenanceCronJobsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list maintenance cron jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListMaintenanceCronJobsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list maintenance cron jobs params.
func (o *ListMaintenanceCronJobsParams) WithTimeout(timeout time.Duration) *ListMaintenanceCronJobsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list maintenance cron jobs params.
func (o *ListMaintenanceCronJobsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list maintenance cron jobs params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListMaintenanceCronJobsParams].
func (o *ListMaintenanceCronJobsParams) WithContext(ctx context.Context) *ListMaintenanceCronJobsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list maintenance cron jobs params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListMaintenanceCronJobsParams].
func (o *ListMaintenanceCronJobsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list maintenance cron jobs params.
func (o *ListMaintenanceCronJobsParams) WithHTTPClient(client *http.Client) *ListMaintenanceCronJobsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list maintenance cron jobs params.
func (o *ListMaintenanceCronJobsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the list maintenance cron jobs params.
func (o *ListMaintenanceCronJobsParams) WithClusterID(clusterID string) *ListMaintenanceCronJobsParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list maintenance cron jobs params.
func (o *ListMaintenanceCronJobsParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the list maintenance cron jobs params.
func (o *ListMaintenanceCronJobsParams) WithProjectID(projectID string) *ListMaintenanceCronJobsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list maintenance cron jobs params.
func (o *ListMaintenanceCronJobsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListMaintenanceCronJobsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
