// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchMaintenanceCronJobParams creates a new PatchMaintenanceCronJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchMaintenanceCronJobParams() *PatchMaintenanceCronJobParams {
	return &PatchMaintenanceCronJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchMaintenanceCronJobParamsWithTimeout creates a new PatchMaintenanceCronJobParams object
// with the ability to set a timeout on a request.
func NewPatchMaintenanceCronJobParamsWithTimeout(timeout time.Duration) *PatchMaintenanceCronJobParams {
	return &PatchMaintenanceCronJobParams{
		timeout: timeout,
	}
}

// NewPatchMaintenanceCronJobParamsWithContext creates a new PatchMaintenanceCronJobParams object
// with the ability to set a context for a request.
func NewPatchMaintenanceCronJobParamsWithContext(ctx context.Context) *PatchMaintenanceCronJobParams {
	return &PatchMaintenanceCronJobParams{
		Context: ctx,
	}
}

// NewPatchMaintenanceCronJobParamsWithHTTPClient creates a new PatchMaintenanceCronJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchMaintenanceCronJobParamsWithHTTPClient(client *http.Client) *PatchMaintenanceCronJobParams {
	return &PatchMaintenanceCronJobParams{
		HTTPClient: client,
	}
}

/*
PatchMaintenanceCronJobParams contains all the parameters to send to the API endpoint

	for the patch maintenance cron job operation.

	Typically these are written to a http.Request.
*/
type PatchMaintenanceCronJobParams struct {

	// Patch.
	Patch interface{}

	// ClusterID.
	ClusterID string

	// MaintenancecronjobID.
	MaintenanceCronJobID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch maintenance cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchMaintenanceCronJobParams) WithDefaults() *PatchMaintenanceCronJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch maintenance cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchMaintenanceCronJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) WithTimeout(timeout time.Duration) *PatchMaintenanceCronJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) WithContext(ctx context.Context) *PatchMaintenanceCronJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) WithHTTPClient(client *http.Client) *PatchMaintenanceCronJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPatch adds the patch to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) WithPatch(patch interface{}) *PatchMaintenanceCronJobParams {
	o.SetPatch(patch)
	return o
}

// SetPatch adds the patch to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) SetPatch(patch interface{}) {
	o.Patch = patch
}

// WithClusterID adds the clusterID to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) WithClusterID(clusterID string) *PatchMaintenanceCronJobParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithMaintenanceCronJobID adds the maintenancecronjobID to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) WithMaintenanceCronJobID(maintenancecronjobID string) *PatchMaintenanceCronJobParams {
	o.SetMaintenanceCronJobID(maintenancecronjobID)
	return o
}

// SetMaintenanceCronJobID adds the maintenancecronjobId to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) SetMaintenanceCronJobID(maintenancecronjobID string) {
	o.MaintenanceCronJobID = maintenancecronjobID
}

// WithProjectID adds the projectID to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) WithProjectID(projectID string) *PatchMaintenanceCronJobParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the patch maintenance cron job params
func (o *PatchMaintenanceCronJobParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchMaintenanceCronJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Patch != nil {
		if err := r.SetBodyParam(o.Patch); err != nil {
			return err
		}
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param maintenancecronjob_id
	if err := r.SetPathParam("maintenancecronjob_id", o.MaintenanceCronJobID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
