// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// AWSTag AWSTag represents a object of AWS tags.
//
// swagger:model AWSTag
type AWSTag struct {

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this a w s tag
func (m *AWSTag) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this a w s tag based on context it is used
func (m *AWSTag) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AWSTag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AWSTag) UnmarshalBinary(b []byte) error {
	var res AWSTag
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
