// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// BackupRestore BackupRestore are s3 settings used for backups and restores of user cluster etcds.
//
// swagger:model BackupRestore
type BackupRestore struct {

	// S3BucketName is the S3 bucket name to use for backup and restore.
	S3BucketName string `json:"s3BucketName,omitempty"`

	// S3Endpoint is the S3 API endpoint to use for backup and restore. Defaults to s3.amazonaws.com.
	S3Endpoint string `json:"s3Endpoint,omitempty"`
}

// Validate validates this backup restore
func (m *BackupRestore) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this backup restore based on context it is used
func (m *BackupRestore) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BackupRestore) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BackupRestore) UnmarshalBinary(b []byte) error {
	var res BackupRestore
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
