// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CiliumClustermesh cilium clustermesh
//
// swagger:model CiliumClustermesh
type CiliumClustermesh struct {

	// Set unique cilium cluster-id
	ClusterID int64 `json:"clusterID,omitempty"`

	// Enable clustermesh resource reconciliation
	Enable *bool `json:"enable,omitempty"`

	// Set ipv4-native-routing-cidr
	IPV4NativeRoutingCIDR string `json:"ipv4NativeRoutingCIDR,omitempty"`
}

// Validate validates this cilium clustermesh
func (m *CiliumClustermesh) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cilium clustermesh based on context it is used
func (m *CiliumClustermesh) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CiliumClustermesh) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CiliumClustermesh) UnmarshalBinary(b []byte) error {
	var res CiliumClustermesh
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
