// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ClusterType cluster type
//
// swagger:model ClusterType
type ClusterType int8

// Validate validates this cluster type
func (m ClusterType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster type based on context it is used
func (m ClusterType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
