// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// Namespace Namespace defines namespace
//
// swagger:model Namespace
type Namespace struct {

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this namespace
func (m *Namespace) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this namespace based on context it is used
func (m *Namespace) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Namespace) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Namespace) UnmarshalBinary(b []byte) error {
	var res Namespace
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
