// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OpenstackCloudSpec OpenstackCloudSpec specifies access data to an OpenStack cloud.
//
// swagger:model OpenstackCloudSpec
type OpenstackCloudSpec struct {

	// +optional
	ApplicationCredentialID string `json:"applicationCredentialID,omitempty"`

	// +optional
	ApplicationCredentialSecret string `json:"applicationCredentialSecret,omitempty"`

	// +optional
	// CreatePodSubnetV6 indicates if podSubnetV6ID not set in OpenstackCloudSpec;
	// tell whether to create a public subnet for the pods with unique local addresses or use a private (internal) CIDR
	CreatePodSubnetV6 bool `json:"createPodSubnetV6,omitempty"`

	// +optional
	Domain string `json:"domain,omitempty"`

	// FloatingIPPool holds the name or ID of the public network
	// The public network is reachable from the outside world
	// and should provide the pool of IP addresses to choose from.
	//
	// When specified, all worker nodes will receive a public ip from this floating ip pool
	//
	// Note that the network is external if the "External" field is set to true
	FloatingIPPool string `json:"floatingIPPool,omitempty"`

	// Network holds the name of the internal network
	// When specified, all worker nodes will be attached to this network. If not specified, a network, subnet and router will be created
	//
	// Note that the network is internal if the "External" field is set to false
	Network string `json:"network,omitempty"`

	// +optional
	Password string `json:"password,omitempty"`

	// +optional
	// PodSubnetV6ID indicates either the client-provided one, or one we created ourselves.
	// If this is set in the cluster create request, it means use this (public) subnet for the pods.
	// Otherwise, use an internal CIDR (as we do now).
	PodSubnetV6ID string `json:"podSubnetV6ID,omitempty"`

	// +optional
	Project string `json:"project,omitempty"`

	// +optional
	ProjectID string `json:"projectID,omitempty"`

	// router ID
	RouterID string `json:"routerID,omitempty"`

	// security groups
	SecurityGroups string `json:"securityGroups,omitempty"`

	// ServerGroupID used as schedule hint shared between all machines in the cluster,
	// When not specified, soft-anti-affinity server group will be automatically created
	// +optional
	ServerGroupID string `json:"serverGroupID,omitempty"`

	// +optional
	SubnetCIDR string `json:"subnetCIDR,omitempty"`

	// subnet ID
	SubnetID string `json:"subnetID,omitempty"`

	// +optional
	SubnetV6CIDR string `json:"subnetV6CIDR,omitempty"`

	// +optional
	SubnetV6ID string `json:"subnetV6ID,omitempty"`

	// Used internally during cluster creation
	// +optional
	Token string `json:"token,omitempty"`

	// Whether or not to use Octavia for LoadBalancer type of Service
	// implementation instead of using Neutron-LBaaS.
	// Attention:Openstack CCM use Octavia as default load balancer
	// implementation since v1.17.0
	//
	// Takes precedence over the 'useOctavia' flag provided at datacenter
	// level if both are specified.
	// +optional
	UseOctavia bool `json:"useOctavia,omitempty"`

	// +optional
	UseToken bool `json:"useToken,omitempty"`

	// +optional
	Username string `json:"username,omitempty"`

	// credentials reference
	CredentialsReference *GlobalSecretKeySelector `json:"credentialsReference,omitempty"`
}

// Validate validates this openstack cloud spec
func (m *OpenstackCloudSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCredentialsReference(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenstackCloudSpec) validateCredentialsReference(formats strfmt.Registry) error {
	if swag.IsZero(m.CredentialsReference) { // not required
		return nil
	}

	if m.CredentialsReference != nil {
		if err := m.CredentialsReference.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("credentialsReference")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("credentialsReference")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this openstack cloud spec based on the context it is used
func (m *OpenstackCloudSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCredentialsReference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenstackCloudSpec) contextValidateCredentialsReference(ctx context.Context, formats strfmt.Registry) error {

	if m.CredentialsReference != nil {

		if swag.IsZero(m.CredentialsReference) { // not required
			return nil
		}

		if err := m.CredentialsReference.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("credentialsReference")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("credentialsReference")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenstackCloudSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenstackCloudSpec) UnmarshalBinary(b []byte) error {
	var res OpenstackCloudSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
