// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// UpdateWindow update window
//
// swagger:model UpdateWindow
type UpdateWindow struct {

	// length
	Length string `json:"length,omitempty"`

	// start
	Start string `json:"start,omitempty"`
}

// Validate validates this update window
func (m *UpdateWindow) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update window based on context it is used
func (m *UpdateWindow) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateWindow) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateWindow) UnmarshalBinary(b []byte) error {
	var res UpdateWindow
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
